---
 - hosts: all
   vars_prompt:
    - name: dvd_dir
      private: no
      prompt: "Enter dvd mount point that you want to be created : " 
   tasks:   
    - file:
        state: directory
        path: "{{ dvd_dir }}"

