---
- name: "This is the playbook for setting up hadoop data node"
  hosts: 13.235.49.175
  vars_prompt:
          - name: master_ip
            prompt: "Enter your master/name ndoe public ip address"
            private: no
  tasks:
   - name: "Copying java jdk rpm file to data node "
     copy:
       src: "/root/ansible/tasks/jdk-8u171-linux-x64.rpm"
       dest: "/root/"
   - name: "Copying hadoop rpm file to data node"
     copy:
       src: "/root/ansible/tasks/hadoop-1.2.1-1.x86_64.rpm"
       dest: "/root/"
   - name: "Installing java jdk software to data node"
     command: "rpm -ivh jdk-8u171-linux-x64.rpm" 
   - name: "Installing hadoop software to data node"
     command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
   - name: "Configuring hdfs-site.xml file"
     blockinfile:
       path: "/etc/hadoop/hdfs-site.xml"
       insertafter: "<configuration>"
       content: |
         <property>
         <name>dfs.data.dir</name>
         <value>/dn</value>
         </property>
   - name: "Configuring core-site.xml file"
     blockinfile:
       path: "/etc/hadoop/core-site.xml"
       insertafter: "<configuration>"
       content: |
         <property>
         <name>fs.default.name</name>
         <value>hdfs://{{ master_ip  }}:9001</value>
         </property>
   - name: "Creating a folder for data node"
     file:
       path: "/dn"
       state: directory
   - name: "Starting the datanode services"
     command: "hadoop-daemon.sh start datanode"

