---
- name: "This is the playbook for setting up hadoop master node"
  hosts: 13.233.82.44
  tasks:
   - name: "Copying java jdk rpm file to master node "
     copy:
       src: "/root/ansible/tasks/jdk-8u171-linux-x64.rpm"
       dest: "/root/"
   - name: "Copying hadoop rpm file to master node"
     copy:
       src: "/root/ansible/tasks/hadoop-1.2.1-1.x86_64.rpm"
       dest: "/root/"
   - name: "Installing java jdk software to master node"
     command: "rpm -ivh jdk-8u171-linux-x64.rpm" 
   - name: "Installing hadoop software to master node"
     command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
   - name: "Configuring hdfs-site.xml file"
     blockinfile:
       path: "/etc/hadoop/hdfs-site.xml"
       insertafter: "<configuration>"
       content: |
         <property>
         <name>dfs.name.dir</name>
         <value>/nn</value>
         </property>
   - name: "Configuring core-site.xml file"
     blockinfile:
       path: "/etc/hadoop/core-site.xml"
       insertafter: "<configuration>"
       content: |
         <property>
         <name>fs.default.name</name>
         <value>hdfs://0.0.0.0:9001</value>
         </property>
   - name: "Creating a folder for data node"
     file:
       path: "/nn"
       state: directory
   - name: "Formatting the name node"
     command: "hadoop namenode -format -force"
   - name: "Starting the namenode services"
     command: "hadoop-daemon.sh start namenode"

